package com.bloodygram;

import org.telegram.messenger.ApplicationLoader;

import java.io.File;

/** Black-red theme asset (generated by Tools/bloodygram/make_theme.js). */
public class BloodyTheme {

    public static final String ASSET = "bloodygram.attheme";

    private static long apkUpdateTime = -1;

    /**
     * Telegram re-copies a theme asset to files/ only when its size changes, so an edited color
     * of the same length would never reach the app. Our theme is re-copied after every APK update.
     */
    public static boolean isStaleCopy(String assetName, File file) {
        if (!ASSET.equals(assetName)) {
            return false;
        }
        if (apkUpdateTime < 0) {
            try {
                apkUpdateTime = ApplicationLoader.applicationContext.getPackageManager().getPackageInfo(ApplicationLoader.applicationContext.getPackageName(), 0).lastUpdateTime;
            } catch (Exception e) {
                apkUpdateTime = 0;
            }
        }
        return file.lastModified() < apkUpdateTime;
    }
}
